title: CMOP
description: >- 
  This is the supplementary material for the CMOP paper
url: "https://vodopijaaljosa.github.io" 
baseurl: "/cmop-web"

# Build settings
remote_theme: pmarsceill/just-the-docs
color_scheme: nice
# search_enabled: false # Use this to disable search

plugins:
  - jekyll-feed
  
kramdown:
    math-engine: katex

# Exclude from processing.
# The following items will not be processed, by default.
exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - README.md
